# This action is an integration test for OIDC workflow
name: OpenID Connect Test
on:
  push:
    branches:
      - '**'
permissions:
  id-token: write
  contents: read
env:
  JFROG_CLI_LOG_LEVEL: DEBUG

jobs:
  OIDC-Test:
    # TODO return after testings
    #    if: contains(github.event.pull_request.labels.*.name, 'safe to test') || github.event_name == 'push'
    name: OIDC-Access integration test
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu, windows, macos ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      # TODO this is for testing purpose before release, remove it after
      - name: Setup JFrog CLI
        id: setup-jfrog-cli
        uses: ./
        env:
          JF_URL: ${{ secrets.JFROG_PLATFORM_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JFROG_ACCESS_TOKEN }}
        with:
          oidc-provider-name: setup-jfrog-cli-test
          download-repository: "generic-local-eyal"
          version: '4.0.0'

      - name: Test JFrog CLI
        run: |
          jf rt ping